import Vue from 'vue'
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faUser,
  faLock,
  faSignOutAlt,
  faCogs,
  faSpinner,
  faCircleNotch,
  faTrash,
  faEdit,
  faTachometerAlt,
  faExclamationTriangle,
  faTasks,
  faExclamation,
  faChartLine,
  faChartBar,
  faChartPie,
  faCalendarAlt,
  faEllipsisH,
  faPrint,
  faFileExport,
  faDownload,
  faWindowClose,
  faSave,
  faChartArea,
  faSearch,
  faPlug,
  faFileAudio,
  faFileWord,
  faCode,
  faDraftingCompass,
  faFolder,
  faAlignJustify,
  faGlobe,
  faMap,
  faFileImage,
  faFilePowerpoint,
  faFileExcel,
  faQuestionCircle,
  faVideo,
  faFilePdf,
  faThumbsUp,
  faChevronRight,
  faStar,
  faNetworkWired,
  faFile,
  faCheck
} from '@fortawesome/free-solid-svg-icons'

import {
  faCcAmex,
  faCcVisa,
  faCcJcb,
  faCcDiscover,
  faCcDinersClub,
  faCcMastercard
} from '@fortawesome/free-brands-svg-icons'

config.autoAddCss = true

library.add(
  faUser,
  faLock,
  faSignOutAlt,
  faCogs,
  faSpinner,
  faCircleNotch,
  faTrash,
  faEdit,
  faTachometerAlt,
  faExclamationTriangle,
  faTasks,
  faExclamation,
  faChartLine,
  faChartBar,
  faChartPie,
  faCalendarAlt,
  faEllipsisH,
  faCcAmex,
  faCcVisa,
  faCcJcb,
  faCcDiscover,
  faCcDinersClub,
  faCcMastercard,
  faPrint,
  faFileExport,
  faDownload,
  faWindowClose,
  faSave,
  faChartArea,
  faSearch,
  faPlug,
  faFileAudio,
  faFileWord,
  faCode,
  faDraftingCompass,
  faFile,
  faFolder,
  faAlignJustify,
  faGlobe,
  faMap,
  faFileImage,
  faFilePowerpoint,
  faFileExcel,
  faQuestionCircle,
  faVideo,
  faFilePdf,
  faThumbsUp,
  faChevronRight,
  faStar,
  faNetworkWired,
  faCheck
)

Vue.component('fa', FontAwesomeIcon)
